### CSE-221710310015-ETTOM.SRINIJA

In [12]:
#NUMPY RANDOM PACKAGE
from numpy import random
print(random.randint(1,100)) #extract random integer digit in given range
print(random.rand()) #float number between 0-1

25
0.0023260093805637094


In [13]:
#to print array  of random values (int)
print(random.randint(100,size=(3)))
print(random.randint(100,size=(3,4)))
print(random.randint(100,size=(3,4,2)))

[47 78 19]
[[99  4  9 66]
 [ 0 79 78 66]
 [90 79 64 58]]
[[[51 42]
  [ 2 52]
  [49 80]
  [ 6 70]]

 [[91 74]
  [83 28]
  [79 52]
  [ 8 76]]

 [[33 78]
  [84 49]
  [89 84]
  [14 77]]]


In [14]:
#print array with floating point
print(random.rand())
print(random.rand(3))
print(random.rand(2,3))
print(random.rand(2,3,2))

0.45995180094535726
[0.31887339 0.64519146 0.19149028]
[[0.34750997 0.63171335 0.52270344]
 [0.42917172 0.1968678  0.52205319]]
[[[0.90823812 0.40448794]
  [0.92987962 0.03922211]
  [0.03020394 0.90047894]]

 [[0.98416151 0.77642251]
  [0.6740563  0.46268657]
  [0.91651189 0.53085413]]]


In [16]:
a=random.randint(100,size=(3,2)).ravel()
print(a)
print(random.choice(a))

[94 56 88 37 28 61]
56


In [18]:
#array from the list of given elements only
random.choice([1,2,3,4,5],size=(3,4))

array([[1, 4, 4, 5],
       [2, 5, 1, 2],
       [5, 2, 3, 2]])

### Pandas:
1. Data manipulation, analysis , cleaning
2. Tabular data ,Unlabelled

### Create a DataFrame:
1. Using 2 dictionaries
2. Simple dictionary ->DataFrame

In [22]:
import pandas as pd
import numpy as np
dict1={'a':1,"b":2,'c':3,'d':4,'e':5}
dict2={'a':5,"b":6,'c':7,'d':8,'e':9}
data={'First':dict1,"Second":dict2} #col_name:col_value
#Creating a dataframe
df=pd.DataFrame(data,dtype=np.int32)
df

First  Second
a      1       5
b      2       6
c      3       7
d      4       8
e      5       9

In [25]:
#simple dictionary->Data frame
d1={"name":["srinija","karthik","sowmya","vardhan"],"address":["hyd","hyd","telangana","rayalaseema"]}
df1=pd.DataFrame(d1)
df1

name      address
0  srinija          hyd
1  karthik          hyd
2   sowmya    telangana
3  vardhan  rayalaseema

In [28]:
#Using Series
s1=pd.Series([1,2,3,4,5,6,7,8,9,10])
s2=pd.Series(['a','b','c','d','e','f','g','h','i','j'])
s3=pd.Series([11.2,34.5,45.3,67.5,1.2,23.4,48.7,78.9,98.1,87.9])
data={"col1":s1,"col2":s2,"col3":s3}
df3=pd.DataFrame(data)
df3

col1 col2  col3
0     1    a  11.2
1     2    b  34.5
2     3    c  45.3
3     4    d  67.5
4     5    e   1.2
5     6    f  23.4
6     7    g  48.7
7     8    h  78.9
8     9    i  98.1
9    10    j  87.9

### Selecting data from DataFrame:
1. loc
2. iloc

In [30]:
df3["col3"]

0    11.2
1    34.5
2    45.3
3    67.5
4     1.2
5    23.4
6    48.7
7    78.9
8    98.1
9    87.9
Name: col3, dtype: float64

In [33]:
df3[["col1","col3"]] #Extracting multiole columns data

col1  col3
0     1  11.2
1     2  34.5
2     3  45.3
3     4  67.5
4     5   1.2
5     6  23.4
6     7  48.7
7     8  78.9
8     9  98.1
9    10  87.9

In [43]:
df3.loc[:,["col1","col2"]] #Extract all rows : specified column

col1 col2
0     1    a
1     2    b
2     3    c
3     4    d
4     5    e
5     6    f
6     7    g
7     8    h
8     9    i
9    10    j

In [42]:
df3.loc[0:5,["col1","col2"]] #Extracting 0-5 rows

col1 col2
0     1    a
1     2    b
2     3    c
3     4    d
4     5    e
5     6    f

In [44]:
type(df3)

pandas.core.frame.DataFrame

In [45]:
#iloc ->indexes the columns
df3.iloc[:,0] #0 is col1 values.

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: col1, dtype: int64

In [48]:
df3.iloc[0:4,0:1] #4th row is not extracted, 1 index->col2 is also not extracted

col1 col2
0     1    a
1     2    b
2     3    c
3     4    d

In [49]:
df3.iloc[0:4,0:2] #col1,col2 are extracted-> 0,1 index

col1 col2
0     1    a
1     2    b
2     3    c
3     4    d

###  Retrieving information from DataFrame:


In [50]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
col1    10 non-null int64
col2    10 non-null object
col3    10 non-null float64
dtypes: float64(1), int64(1), object(1)
memory usage: 368.0+ bytes


In [51]:
df3.shape

(10, 3)

In [52]:
df3.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [53]:
df3.index

RangeIndex(start=0, stop=10, step=1)

### Viewing data from DataFrame:


In [55]:
df3.head() #Returns first 5 rows of DataFrame by default

col1 col2  col3
0     1    a  11.2
1     2    b  34.5
2     3    c  45.3
3     4    d  67.5
4     5    e   1.2

In [58]:
df3.head(3) #until 3 rows only 

col1 col2  col3
0     1    a  11.2
1     2    b  34.5
2     3    c  45.3

In [59]:
df3.head(7)#Can print more than 5 rows too if given values


col1 col2  col3
0     1    a  11.2
1     2    b  34.5
2     3    c  45.3
3     4    d  67.5
4     5    e   1.2
5     6    f  23.4
6     7    g  48.7

In [60]:
df3.tail() #default set to extract last 5 rows

col1 col2  col3
5     6    f  23.4
6     7    g  48.7
7     8    h  78.9
8     9    i  98.1
9    10    j  87.9

In [61]:
df3.tail(2) #extracting 2 tail rows

col1 col2  col3
8     9    i  98.1
9    10    j  87.9

In [62]:
df3.sample() #extract any row randomly

col1 col2  col3
2     3    c  45.3

In [65]:
df3.sample(3) #extracting 3 rows randomly

col1 col2  col3
4     5    e   1.2
3     4    d  67.5
0     1    a  11.2

In [66]:
df3.describe()

col1       col3
count  10.00000  10.000000
mean    5.50000  49.670000
std     3.02765  32.912107
min     1.00000   1.200000
25%     3.25000  26.175000
50%     5.50000  47.000000
75%     7.75000  76.050000
max    10.00000  98.100000

In [69]:
df3 = df3.rename(columns={"col1":"First","col2":"Second","col3":"Third"})
#renaming columns
df3

First Second  Third
0      1      a   11.2
1      2      b   34.5
2      3      c   45.3
3      4      d   67.5
4      5      e    1.2
5      6      f   23.4
6      7      g   48.7
7      8      h   78.9
8      9      i   98.1
9     10      j   87.9