## Naive Bayes:

In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv("https://raw.githubusercontent.com/Mounika-Kajjam/Datasets/master/spam.csv",
                encoding='latin-1')
data
#encoding is used because there are some kind of emojis in the data
#Therefore to display that we need to use encoding

v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [3]:
data.shape

(5572, 5)

In [4]:
data.drop(['Unnamed: 2','Unnamed: 3','Unnamed: 4'],axis=1,inplace=True)
data.shape

(5572, 2)

In [5]:
#V1->Output
#V2->Input
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(data.v2,data.v1,test_size=0.2,random_state=0)

In [6]:
X_train

1114    No no:)this is kallis home ground.amla home to...
3589    I am in escape theatre now. . Going to watch K...
3095    We walked from my moms. Right on stagwood pass...
1012       I dunno they close oredi not... ÌÏ v ma fan...
3320                               Yo im right by yo work
                              ...                        
4931                Match started.india  &lt;#&gt;  for 2
3264    44 7732584351, Do you want a New Nokia 3510i c...
1653    I was at bugis juz now wat... But now i'm walk...
2607    :-) yeah! Lol. Luckily i didn't have a starrin...
2732    How dare you stupid. I wont tell anything to y...
Name: v2, Length: 4457, dtype: object

In [7]:
#CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer
#creating an object
count_vect= CountVectorizer()

In [8]:
#Generate the word counts in the documents
word_count_vect= count_vect.fit(X_train)
#To get the feature names
word_count_vect.get_feature_names()

['00',
 '000',
 '000pes',
 '008704050406',
 '0089',
 '0121',
 '01223585236',
 '01223585334',
 '0125698789',
 '02',
 '0207',
 '02072069400',
 '02073162414',
 '02085076972',
 '021',
 '03',
 '04',
 '0430',
 '05',
 '0578',
 '06',
 '07008009200',
 '07099833605',
 '07123456789',
 '0721072',
 '07734396839',
 '07742676969',
 '07753741225',
 '0776xxxxxxx',
 '07781482378',
 '07786200117',
 '077xxx',
 '078',
 '07808247860',
 '07808726822',
 '07821230901',
 '078498',
 '07880867867',
 '0789xxxxxxx',
 '07946746291',
 '0796xxxxxx',
 '07973788240',
 '07xxxxxxxxx',
 '08',
 '0800',
 '08000407165',
 '08000839402',
 '08000930705',
 '08000938767',
 '08001950382',
 '08002888812',
 '08002986030',
 '08002986906',
 '08006344447',
 '0808',
 '08081263000',
 '08081560665',
 '0825',
 '0844',
 '08448350055',
 '08448714184',
 '0845',
 '08452810071',
 '08452810073',
 '08452810075over18',
 '0870',
 '08700435505150p',
 '08700469649',
 '08700621170150p',
 '08701213186',
 '08701237397',
 '08701417012',
 '08701417012150p'

In [9]:
#coverting/trasforming the data into an array from a list
doc_array = word_count_vect.transform(X_train)
doc_array

<4457x7612 sparse matrix of type '<class 'numpy.int64'>'
	with 58826 stored elements in Compressed Sparse Row format>

In [10]:
#converting into array
doc_array = word_count_vect.transform(X_train).toarray()
doc_array

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [11]:
#converting the array into a dataframe
feature_matrix = doc_array = pd.DataFrame(doc_array,columns=word_count_vect.get_feature_names())
feature_matrix

00  000  000pes  008704050406  0089  0121  01223585236  01223585334  \
0      0    0       0             0     0     0            0            0   
1      0    0       0             0     0     0            0            0   
2      0    0       0             0     0     0            0            0   
3      0    0       0             0     0     0            0            0   
4      0    0       0             0     0     0            0            0   
...   ..  ...     ...           ...   ...   ...          ...          ...   
4452   0    0       0             0     0     0            0            0   
4453   0    0       0             0     0     0            0            0   
4454   0    0       0             0     0     0            0            0   
4455   0    0       0             0     0     0            0            0   
4456   0    0       0             0     0     0            0            0   

      0125698789  02  ...  ì_  ì¼1  ìï  ó_  û_  û_thanks  ûï  ûïharry  ûò  \
0              0   0  ...   0    0   0   0   0         0   0        0   0   
1              0   0  ...   0    0   0   0   0         0   0        0   0   
2              0   0  ...   0    0   0   0   0         0   0        0   0   
3              0   0  ...   0    0   1   0   0         0   0        0   0   
4              0   0  ...   0    0   0   0   0         0   0        0   0   
...          ...  ..  ...  ..  ...  ..  ..  ..       ...  ..      ...  ..   
4452           0   0  ...   0    0   0   0   0         0   0        0   0   
4453           0   0  ...   0    0   0   0   0         0   0        0   0   
4454           0   0  ...   1    0   1   0   0         0   0        0   0   
4455           0   0  ...   0    0   0   0   0         0   0        0   0   
4456           0   0  ...   0    0   0   0   0         0   0        0   0   

      ûówell  
0          0  
1          0  
2          0  
3          0  
4          0  
...      ...  
4452       0  
4453       0  
4454       0  
4455       0  
4456       0  

[4457 rows x 7612 columns]

Why fit_transform is performed only on training data?

Now if we specifically talk about CountVectorizer, then consider the following example, let your training data have the following 3 sentences:
1. Dog is black.
2. Sky is blue.
Dog is dancing.
Now the vocabulary set for this will be {Dog, is, black, sky, blue, dancing}. Now the algorithm that you will train will try to learn rules based on the count of these 6 vocabulary terms. So your features will be vectors of length 6.
Now if the test set is as follows:
1. Dog is white.
2. Sky is black.
Now if you use the test data for fit_transform your vocabulary will look like {Dog, white, is, Sky, black}. So here your each document will be represented by a vector of length 5 denoting the counts of each of these terms. Now, this will be like comparing apples with oranges. You learn rules for counts of the previous vocabulary and those rules can not be applied to this vocabulary. This is the reason why you only fit on the training data.


## TFIDF Vetctorizer

In [12]:
#importing
from sklearn.feature_extraction.text import TfidfVectorizer
#creating an object
tfidf=TfidfVectorizer()

In [13]:
#Apllyting the tfidf to the data(X_train)
X_train_transformed = tfidf.fit_transform(X_train)
X_train_transformed

<4457x7612 sparse matrix of type '<class 'numpy.float64'>'
	with 58826 stored elements in Compressed Sparse Row format>

In [14]:
X_test_transformed = tfidf.transform(X_test)
X_test_transformed

<1115x7612 sparse matrix of type '<class 'numpy.float64'>'
	with 13975 stored elements in Compressed Sparse Row format>

In [15]:
#Feature names:
tfidf.get_feature_names()

['00',
 '000',
 '000pes',
 '008704050406',
 '0089',
 '0121',
 '01223585236',
 '01223585334',
 '0125698789',
 '02',
 '0207',
 '02072069400',
 '02073162414',
 '02085076972',
 '021',
 '03',
 '04',
 '0430',
 '05',
 '0578',
 '06',
 '07008009200',
 '07099833605',
 '07123456789',
 '0721072',
 '07734396839',
 '07742676969',
 '07753741225',
 '0776xxxxxxx',
 '07781482378',
 '07786200117',
 '077xxx',
 '078',
 '07808247860',
 '07808726822',
 '07821230901',
 '078498',
 '07880867867',
 '0789xxxxxxx',
 '07946746291',
 '0796xxxxxx',
 '07973788240',
 '07xxxxxxxxx',
 '08',
 '0800',
 '08000407165',
 '08000839402',
 '08000930705',
 '08000938767',
 '08001950382',
 '08002888812',
 '08002986030',
 '08002986906',
 '08006344447',
 '0808',
 '08081263000',
 '08081560665',
 '0825',
 '0844',
 '08448350055',
 '08448714184',
 '0845',
 '08452810071',
 '08452810073',
 '08452810075over18',
 '0870',
 '08700435505150p',
 '08700469649',
 '08700621170150p',
 '08701213186',
 '08701237397',
 '08701417012',
 '08701417012150p'

In [16]:
 #Returns the position of the words in the sparse martix
tfidf.vocabulary_

{'no': 4700,
 'this': 6717,
 'is': 3682,
 'kallis': 3818,
 'home': 3415,
 'ground': 3197,
 'amla': 905,
 'town': 6866,
 'durban': 2459,
 'am': 897,
 'in': 3575,
 'escape': 2599,
 'theatre': 6683,
 'now': 4750,
 'going': 3117,
 'to': 6799,
 'watch': 7254,
 'kavalan': 3830,
 'few': 2769,
 'minutes': 4418,
 'we': 7274,
 'walked': 7218,
 'from': 2967,
 'my': 4576,
 'moms': 4477,
 'right': 5673,
 'on': 4841,
 'stagwood': 6309,
 'pass': 5006,
 'winterstone': 7392,
 'left': 3991,
 'victors': 7137,
 'hill': 3371,
 'address': 780,
 'lt': 4170,
 'gt': 3204,
 'dunno': 2458,
 'they': 6701,
 'close': 1815,
 'oredi': 4890,
 'not': 4737,
 'ìï': 7604,
 'ma': 4211,
 'fan': 2719,
 'yo': 7557,
 'im': 3549,
 'by': 1552,
 'work': 7450,
 'its': 3698,
 'ur': 7063,
 'luck': 4175,
 'love': 4150,
 'someone': 6179,
 'fortune': 2907,
 'the': 6681,
 'one': 4845,
 'who': 7354,
 'loves': 4158,
 'but': 1538,
 'he': 3306,
 'also': 889,
 'knows': 3886,
 'about': 723,
 'lunch': 4182,
 'menu': 4367,
 'only': 4851,
 'da':

In [17]:
#Idf of the terms:
#Weights assigned to the words are returned
tfidf.idf_

array([7.09987042, 6.35793308, 8.70930833, ..., 8.70930833, 7.61069604,
       8.70930833])

In [18]:
#applying the naive bayes algorithm
#Import BernoulliNB
from sklearn.naive_bayes import BernoulliNB
#creating object
model_BernNB=BernoulliNB()

In [19]:
#Applying algorithm to the data
#Objectname.fit(Input,Output)
model_BernNB.fit(X_train_transformed,y_train)


BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [21]:
# predict on test data
# syntax: objectname.predict(input values)
y_test_pred=model_BernNB.predict(X_test_transformed)

In [22]:
# comparing the actual values with the predicted values
from sklearn.metrics import confusion_matrix,classification_report
confusion_matrix(y_test,y_test_pred)

array([[948,   1],
       [ 36, 130]], dtype=int64)

In [23]:
print(classification_report(y_test,y_test_pred))

              precision    recall  f1-score   support

         ham       0.96      1.00      0.98       949
        spam       0.99      0.78      0.88       166

    accuracy                           0.97      1115
   macro avg       0.98      0.89      0.93      1115
weighted avg       0.97      0.97      0.97      1115



In [28]:
#Testing a single message ->Spam or Ham
new_message=pd.Series('Last few days to grab the free passes with 40% discount')
#Calculate the tfidf values for the new message
new_message_transformed  = tfidf.transform(new_message)

In [29]:
#Predict the new message
model_BernNB.predict(new_message_transformed)

array(['ham'], dtype='<U4')